// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuiNXEKYozuA_xGX_Rno-6X3hfGpeRuCI',
    appId: '1:349874521433:web:915cde84bebd0991917848',
    messagingSenderId: '349874521433',
    projectId: 'easyway-9dad3',
    authDomain: 'easyway-9dad3.firebaseapp.com',
    storageBucket: 'easyway-9dad3.firebasestorage.app',
    measurementId: 'G-X5JPT090TV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgXXX0XVFzmcE4jsi-yT_B9hsuYxmUJAs',
    appId: '1:349874521433:android:869de10c198e7976917848',
    messagingSenderId: '349874521433',
    projectId: 'easyway-9dad3',
    storageBucket: 'easyway-9dad3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_zIRtYltb93Ujgmxktrh418FjjZ3tkms',
    appId: '1:349874521433:ios:5f778bda298796dc917848',
    messagingSenderId: '349874521433',
    projectId: 'easyway-9dad3',
    storageBucket: 'easyway-9dad3.firebasestorage.app',
    iosBundleId: 'com.example.nawahTeachers',
  );
}
